### PR TITLE
Updated to 7.3.2

### PR DESCRIPTION
**Pull request by ashinagawa**
Updated VungleAds SDK to `7.3.2`.

### CODE REVIEW

**Review by johnmaivungle — COMMENTED** [review]
I'm still noticing that when I run the project, it is pointing to 7.0.1 on the app. 
Screenshot 2024-05-01 at 12 30 29 PM

Screenshot 2024-05-01 at 12 30 41 PM

Just want to confirm, do I have the right pod for the VungleAds? When I run a `pod install --repo-update` it is still pointing to 7.0.1. @ashinagawa

**Comment by johnmaivungle** [comment]
It looks like I need to manually specify 7.3.2 in cocoapods in order to get the 7.3.2 SDK. Might have to with my Podfile cache stored locally. 
Screenshot 2024-05-01 at 12 33 55 PM

**Comment by ashinagawa** [comment]
@johnmaivungle 
Or, you might need to remove `Podfile.lock`

**Review by ManojBudumuru-vungle — APPROVED** [review]

**Comment by johnmaivungle** [comment]
@ashinagawa Yeah, by manually specifying 7.3.2, I was able to get the right SDK version. Aside from that, I was able to to get the proper version.

**Review by johnmaivungle — APPROVED** [review]

**Pull request merged**
